import type { TripData } from "./types";

export const seedData: TripData = {
  trip: {
    id: "trip-2026-europe",
    name: "2026 中歐之旅",
    startDate: "2026-05-18",
    endDate: "2026-05-31",
    route: "Vancouver → Vienna → Prague → Budapest → Bratislava → Vienna → Vancouver",
    mainCurrency: "HKD",
    travelers: ["Chris"]
  },

  itinerary: [
    {
      id: "itin-yvr-fra",
      title: "出發航班：YVR 溫哥華 → FRA 法蘭克福",
      city: "Vancouver",
      date: "2026-05-18",
      timeBlock: "Evening",
      address: "Vancouver International Airport (YVR)",
      notes: "Condor DE2455｜17:50 起飛｜經濟艙｜空中巴士 A330-900｜到達 FRA：5月19日 12:45｜轉機時間 1小時45分。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Vancouver+International+Airport",
      completed: false
    },
    {
      id: "itin-fra-vie",
      title: "轉機航班：FRA 法蘭克福 → VIE 維也納",
      city: "Frankfurt / Vienna",
      date: "2026-05-19",
      timeBlock: "Afternoon",
      address: "Frankfurt Airport Terminal 1",
      notes: "Condor DE4345｜14:30 起飛｜15:50 抵達 VIE 維也納國際機場 T1。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Vienna+International+Airport",
      completed: false
    },
    {
      id: "itin-vienna-checkin",
      title: "抵達維也納 + 入住 lyf Schönbrunn Vienna",
      city: "Vienna",
      date: "2026-05-19",
      timeBlock: "Evening",
      address: "12 Breitenfurter Straße, 12. Meidling, 1120 Vienna, Austria",
      notes: "抵達後前往酒店 check-in，附近晚餐，整理行李。",
      estimatedCost: 200,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=lyf+Schönbrunn+Vienna",
      completed: false
    },
    {
      id: "itin-vienna-prague-train",
      title: "火車：維也納 → 布拉格",
      city: "Vienna / Prague",
      date: "2026-05-23",
      timeBlock: "Afternoon",
      address: "Vienna",
      notes: "12:10 出發，16:23 到達。13:04 落車轉車 1 次。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "",
      completed: false
    },
    {
      id: "itin-prague-old-town",
      title: "布拉格老城區夜遊",
      city: "Prague",
      date: "2026-05-23",
      timeBlock: "Evening",
      address: "Old Town Square, Prague",
      notes: "抵達後輕鬆行老城廣場、查理大橋附近，適合夜景同街拍。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Old+Town+Square+Prague",
      completed: false
    },
    {
      id: "itin-prague-budapest-train",
      title: "火車：布拉格 → 布達佩斯",
      city: "Prague / Budapest",
      date: "2026-05-26",
      timeBlock: "Morning",
      address: "Prague",
      notes: "07:37 出發，14:28 到達布達佩斯。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "",
      completed: false
    },
    {
      id: "itin-budapest-checkin",
      title: "抵達布達佩斯 + 入住 Airbnb",
      city: "Budapest",
      date: "2026-05-26",
      timeBlock: "Afternoon",
      address: "Kisfaludy utca 16, 1st floor, Door 7, Budapest, 1082, Hungary",
      notes: "抵達後入住，附近晚餐。",
      estimatedCost: 200,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Kisfaludy+utca+16+Budapest",
      completed: false
    },
    {
      id: "itin-budapest-bath",
      title: "布達佩斯溫泉浴場",
      city: "Budapest",
      date: "2026-05-27",
      timeBlock: "Afternoon",
      address: "Budapest",
      notes: "記得帶泳衣、拖鞋，預先查門票。",
      estimatedCost: 300,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Budapest+thermal+bath",
      completed: false
    },
    {
      id: "itin-budapest-bratislava-bus",
      title: "巴士：布達佩斯 → Bratislava",
      city: "Budapest / Bratislava",
      date: "2026-05-29",
      timeBlock: "Afternoon",
      address: "Budapest",
      notes: "12:30 出發，15:10 到達。巴士，座位不能一起坐。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "",
      completed: false
    },
    {
      id: "itin-bratislava-old-town",
      title: "Bratislava 老城散步",
      city: "Bratislava",
      date: "2026-05-29",
      timeBlock: "Evening",
      address: "Bratislava Old Town",
      notes: "短途夜遊，晚餐，睇老城夜景。",
      estimatedCost: 150,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Bratislava+Old+Town",
      completed: false
    },
    {
      id: "itin-bratislava-vienna-train",
      title: "火車：Bratislava → Vienna",
      city: "Bratislava / Vienna",
      date: "2026-05-30",
      timeBlock: "Afternoon",
      address: "Bratislava",
      notes: "12:50 出發，13:46 到達。手機 App 買飛。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "",
      completed: false
    },
    {
      id: "itin-vienna-final-night",
      title: "維也納最後一晚 + 入住 District Living",
      city: "Vienna",
      date: "2026-05-30",
      timeBlock: "Evening",
      address: "Donau-City-Straße 3, 22. Donaustadt, 1220 Vienna, Austria",
      notes: "整理行李，準備翌日離開維也納。",
      estimatedCost: 200,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=District+Living+Vienna",
      completed: false
    },
    {
      id: "itin-vie-fra-return",
      title: "離開歐洲：VIE 維也納 → FRA 法蘭克福",
      city: "Vienna / Frankfurt",
      date: "2026-05-31",
      timeBlock: "Afternoon",
      address: "Vienna International Airport",
      notes: "Condor DE4348｜16:55 VIE T1 起飛｜18:15 到達 FRA T1｜轉機時間約 20小時10分。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Vienna+International+Airport",
      completed: false
    },
    {
      id: "itin-fra-yvr-return",
      title: "回程航班：FRA 法蘭克福 → YVR 溫哥華",
      city: "Frankfurt / Vancouver",
      date: "2026-06-01",
      timeBlock: "Afternoon",
      address: "Frankfurt Airport Terminal 1",
      notes: "6月1日 14:25 由 FRA 起飛回溫哥華。因 app 行程結束日暫設 5月31日，這筆可作延伸提醒。",
      estimatedCost: 0,
      currency: "HKD",
      googleMapsLink: "https://www.google.com/maps/search/?api=1&query=Frankfurt+Airport+Terminal+1",
      completed: false
    }
  ],

  accommodations: [
    {
      id: "acc-vienna-lyf",
      city: "Vienna",
      name: "lyf Schönbrunn Vienna",
      type: "Hotel",
      checkInDate: "2026-05-19",
      checkOutDate: "2026-05-23",
      address: "12 Breitenfurter Straße, 12. Meidling, 1120 Vienna, Austria",
      totalCost: 2700,
      currency: "HKD",
      nights: 4,
      averageCostPerNight: 675,
      bookingReference: "",
      notes: ""
    },
    {
      id: "acc-prague-airbnb",
      city: "Prague",
      name: "Airbnb",
      type: "Airbnb",
      checkInDate: "2026-05-23",
      checkOutDate: "2026-05-26",
      address: "Hellichova 394/7, Prague 1, Prague 118 00, Czech Republic",
      totalCost: 2927.74,
      currency: "HKD",
      nights: 3,
      averageCostPerNight: 975.91,
      bookingReference: "",
      notes: ""
    },
    {
      id: "acc-budapest-airbnb",
      city: "Budapest",
      name: "Airbnb",
      type: "Airbnb",
      checkInDate: "2026-05-26",
      checkOutDate: "2026-05-29",
      address: "Kisfaludy utca 16, 1st floor, Door 7, Budapest, 1082, Hungary",
      totalCost: 2107.51,
      currency: "HKD",
      nights: 3,
      averageCostPerNight: 702.5,
      bookingReference: "",
      notes: ""
    },
    {
      id: "acc-bratislava-airbnb",
      city: "Bratislava",
      name: "Airbnb",
      type: "Airbnb",
      checkInDate: "2026-05-29",
      checkOutDate: "2026-05-30",
      address: "Budovateľská 1054, First floor, Bratislava, Bratislavský kraj 821 08, Slovakia",
      totalCost: 576.8,
      currency: "HKD",
      nights: 1,
      averageCostPerNight: 576.8,
      bookingReference: "",
      notes: ""
    },
    {
      id: "acc-vienna-district",
      city: "Vienna",
      name: "District Living",
      type: "Hotel",
      checkInDate: "2026-05-30",
      checkOutDate: "2026-05-31",
      address: "Donau-City-Straße 3, 22. Donaustadt, 1220 Vienna, Austria",
      totalCost: 620,
      currency: "HKD",
      nights: 1,
      averageCostPerNight: 620,
      bookingReference: "",
      notes: ""
    }
  ],

  transport: [
    {
      id: "tr-yvr-fra",
      fromCity: "Vancouver",
      toCity: "Frankfurt",
      date: "2026-05-18",
      transportType: "Flight",
      departureTime: "17:50",
      arrivalTime: "12:45",
      departureStation: "YVR 溫哥華國際機場 M",
      arrivalStation: "FRA 法蘭克福機場 T1",
      cost: 0,
      currency: "HKD",
      bookingLink: "",
      notes: "Condor DE2455｜經濟艙｜空中巴士 A330-900｜5月19日抵達。",
      confirmed: true
    },
    {
      id: "tr-fra-vie",
      fromCity: "Frankfurt",
      toCity: "Vienna",
      date: "2026-05-19",
      transportType: "Flight",
      departureTime: "14:30",
      arrivalTime: "15:50",
      departureStation: "FRA 法蘭克福機場 T1",
      arrivalStation: "VIE 維也納國際機場 T1",
      cost: 0,
      currency: "HKD",
      bookingLink: "",
      notes: "Condor DE4345｜轉機時間 1小時45分。",
      confirmed: true
    },
    {
      id: "tr-vienna-prague",
      fromCity: "Vienna",
      toCity: "Prague",
      date: "2026-05-23",
      transportType: "Train",
      departureTime: "12:10",
      arrivalTime: "16:23",
      departureStation: "Vienna",
      arrivalStation: "Prague",
      cost: 0,
      currency: "HKD",
      bookingLink: "",
      notes: "13:04 落車轉車 1 次。",
      confirmed: true
    },
    {
      id: "tr-prague-budapest",
      fromCity: "Prague",
      toCity: "Budapest",
      date: "2026-05-26",
      transportType: "Train",
      departureTime: "07:37",
      arrivalTime: "14:28",
      departureStation: "Prague",
      arrivalStation: "Budapest",
      cost: 0,
      currency: "HKD",
      bookingLink: "",
      notes: "",
      confirmed: true
    },
    {
      id: "tr-budapest-bratislava",
      fromCity: "Budapest",
      toCity: "Bratislava",
      date: "2026-05-29",
      transportType: "Bus",
      departureTime: "12:30",
      arrivalTime: "15:10",
      departureStation: "Budapest",
      arrivalStation: "Bratislava",
      cost: 0,
      currency: "HKD",
      bookingLink: "",
      notes: "巴士，冇得一齊坐。",
      confirmed: true
    },
    {
      id: "tr-bratislava-vienna",
      fromCity: "Bratislava",
      toCity: "Vienna",
      date: "2026-05-30",
      transportType: "Train",
      departureTime: "12:50",
      arrivalTime: "13:46",
      departureStation: "Bratislava",
      arrivalStation: "Vienna",
      cost: 0,
      currency: "HKD",
      bookingLink: "",
      notes: "手機 App 買飛。",
      confirmed: true
    },
    {
      id: "tr-vie-fra",
      fromCity: "Vienna",
      toCity: "Frankfurt",
      date: "2026-05-31",
      transportType: "Flight",
      departureTime: "16:55",
      arrivalTime: "18:15",
      departureStation: "VIE 維也納國際機場 T1",
      arrivalStation: "FRA 法蘭克福機場 T1",
      cost: 0,
      currency: "HKD",
      bookingLink: "",
      notes: "Condor DE4348｜轉機時間約 20小時10分。",
      confirmed: true
    }
  ],

  expenses: [
    {
      id: "exp-accommodation-total",
      date: "2026-05-19",
      category: "Accommodation",
      title: "住宿總額",
      amount: 8932.05,
      currency: "HKD",
      paidBy: "Chris",
      notes: "根據已訂住宿總額。"
    }
  ],

  wishlist: [
    {
      id: "wish-vienna-cafe",
      placeName: "維也納咖啡館",
      city: "Vienna",
      category: "Cafe",
      priority: "Must Go",
      address: "Vienna",
      estimatedCost: 200,
      currency: "HKD",
      estimatedDuration: "1–2 小時",
      notes: "中歐旅行必去，適合休息同影相。",
      googleMapsLink: ""
    }
  ],

  documents: [
    {
      id: "doc-flight",
      title: "來回機票資料",
      type: "Flight Ticket",
      relatedCity: "Vancouver / Frankfurt / Vienna",
      date: "2026-05-18",
      link: "",
      notes: "YVR → FRA → VIE；VIE → FRA → YVR。"
    },
    {
      id: "doc-placeholder",
      title: "火車票 / 巴士票 / 酒店確認",
      type: "Other",
      relatedCity: "All",
      date: "2026-05-19",
      link: "",
      notes: "之後可以貼 booking link 或 QR code link。"
    }
  ]
};
